#!/bin/bash

#------------------------------------------------------------------------------
# Homebrew Casks
#------------------------------------------------------------------------------

## Casks Distributed as packages required typing password, so they're moved last
brew cask install sf-symbols
brew cask install microsoft-azure-storage-explorer
brew cask install microsoft-edge
brew cask install microsoft-teams
brew cask install powershell
brew cask install oracle-jdk
brew cask install parallels
brew cask install choosy
brew cask install vmware-fusion
brew cask install zoomus

## Regular apps
brew cask install android-studio
brew cask install alfred
brew cask install azure-data-studio
brew cask install bartender
brew cask install docker
brew cask install firefox
brew cask install fork
brew cask install gitkraken
brew cask install google-chrome
brew cask install handbrake
brew cask install imazing
brew cask install itsycal
brew cask install keyboard-cleaner
brew cask install marked
brew cask install postman
brew cask install reflector
brew cask install rider
brew cask install skype
brew cask install staruml
brew cask install upwork
brew cask install visual-studio-code
brew cask install vlc
brew cask install whatsapp
brew cask install iterm2

## Quicklook Plugins
brew cask install qlcolorcode 
brew cask install qlstephen
brew cask install qlmarkdown
brew cask install quicklook-json
brew cask install qlimagesize
brew cask install suspicious-package
brew cask install provisionql quicklookapk
