#! /bin/bash
# Reference: http://feedback.choosyosx.com/forums/6165-general/suggestions/12480483-add-export-import-of-rules-and-setting

choosy_config_file_name="behaviours.plist"
choosy_data_path="${HOME}/Library/Application Support/Choosy"
choosy_config_file="${choosy_data_path}/${choosy_config_file_name}"

cp "${choosy_config_file}" "data/choosy/${choosy_config_file_name}"
